### ISSUE TITLE
Interferenza tra Gameplay e Debug

### ISSUE THREAD

**Issue by CristiJ92** [frigierim/ggj-tracking#1]
V.0.1.1
Aprendo la finestra di debug il gameplay di sottofondo continua (ok) e se si usano i tasti per muoversi ecc si agisce sia sul gameplay che sulla finestra il che è un problema visto che cambia le impostazioni a caso... è possibile evitare il conflitto? magari imponendo alla finestra l'interazione solo col mouse?

**Comment by frigierim** [comment]
Mi sembrava di averlo risolto... qualcuno ha verificato l'ultima release?

**Comment by CristiJ92** [comment]
sembra risolto, chiudo.
dobbiamo provare a riprendere il ritmo... purtroppo fino giugno (o luglio) sono parecchio impegnato e potrò dedicarmi al progetto solo i weekend e sopratutto sui docs di GDD che sono parecchio indietro. 
Prova a confrontarti con gli altri per fare testing e ricerca bug
