### ISSUE TITLE
Richiamo finestra debug

### ISSUE THREAD

**Issue by CristiJ92** [frigierim/ggj-tracking#16]
v.0.0.17

il gioco non è pubblico... singolo tasto anzichè combinazione? renderebbe più veloce i testing...
propongo shift+F10 -> F12 , se non possibile fai te @frigierim 

se mai sto gioco sarà dato in pasto a qualcuno, complicheremo l'accesso a questa finestra.

**Comment by frigierim** [comment]
Ok, messo F12.
