### ISSUE TITLE
il cheat Collisions funziona solo su ground 

### ISSUE THREAD

**Issue by CristiJ92** [frigierim/ggj-tracking#17]
v.0.0.17

Collisions funziona solo su ground,  non funziona su altri livelli.
sembra una macro che carica ground con collisioni visibili.

step:
1)avvia gioco
2)play
3)cheat jump to giardino
4)cheat collisions

p.s. visto che metti mano su Collisions, si può fare in modo che non ricarica il mappa e gameplay? è un grosso limite... eventualmente ti faccio in'altro issue?

**Comment by frigierim** [comment]
Dovrebbe essere sistemato. Purtroppo non posso fare a meno di ricaricare il gameplay per mostrare le collisioni, per come funziona Godot (o almeno per quel che ho capito io), ma almeno adesso dovrebbe ritornare sullo stesso livello in cui eri prima di cliccare su Collisions.

**Comment by CristiJ92** [comment]
V.0.0.20
il problema persiste, il gioco si blocca

per quanto riguarda il ricaricamento della mappa apro un nuovo issue

**Comment by frigierim** [comment]
Non riesco a riprodurre il problema seguendo i passi elencati nel post originale. Cosa intendi per "il gioco si blocca"? Considera anche che nel livello Giardino non è stato fatto lavoro sugli ostacoli, quindi le uniche aree di collisione visibili dovrebbero essere le note, le entrate/uscite dal livello, e il giocatore.

**Comment by CristiJ92** [comment]
v.0.0.20

rimane così:

![image](https://user-images.githubusercontent.com/45758943/55293452-09536a80-53f7-11e9-92cc-a509c4e0a7de.png)

per ricreare il problema prova a smanettare più volte jump to e collision cambiando continuamente il livello, non capita sempre...

ho provato un po di volte, le ultime cose che ho fatto sono caricare giardino e checkare collision e rimani bloccato come in figura sopra con contatore fermo a 0

v.0.0.22

ho provato a riprodurre ma non mi è capitato ma secondo me c'è anche qui, semplicemente non ho avuto "fortuna"

**Comment by CristiJ92** [comment]
v.0.0.25
difficile da verificare, provato e non da problemi.
chiudo e riapro se si presenta di nuovo il problema.
