### ISSUE TITLE
miglioramenti grafici finestra debug

### ISSUE THREAD

**Issue by CristiJ92** [frigierim/ggj-tracking#18]
v.0.0.17

l'obiettivo è rendere più leggibile e user friendly la finestra di debug.

richieste:
- switch colonne jhonny kenny in modo che rispecchi l'ordine 1° e 2° player
- cambiare font (usare uno più leggibile)
- diminuire grandezza font
- riposizionare valore position
- riposizionare collisions
- ridimensionare bottone "jump to"
- ridimensionare il selettore di livello

@frigierim hai carta bianca... cerca di rendere guardabile sta schermata di debug XD

prima o poi, quando avrò tempo, imparerò a smanettare su Godot così le gestisco direttamente io ste cavolate..

**Comment by frigierim** [comment]
Vabbè, ho girato le colonne e messo i colori... più di così da programmatore non riesco a fare XD
