### ISSUE TITLE
Aggiungere cheat per Debug/Testing

### ISSUE THREAD

**Issue by CristiJ92** [frigierim/ggj-tracking#20]
Sarebbe utile avere qualche cheat ai fini di debug/testing...

al momento mi viene da proporre:
-solo jhon OK
-solo kenny OK
-speed OK

**Comment by CristiJ92** [comment]
potresti anche fare in modo che la versione della release sia sempre visibile?

**Comment by CristiJ92** [comment]
altre feature:
- X, Y e rotazione attuale stampate su schermo OK

**Comment by frigierim** [comment]
Aggiunta una schermata di debug, si attiva e disattiva con la combinazione di tasti Shift+ESC
Si possono cambiare la velocità dei personaggi, la durata del turno, se abilitare o no i personaggi.
Viene inoltre visualizzata la posizione e la versione corrente.

**Comment by CristiJ92** [comment]
- "mostrare a video un overlay con le maschere di collisione" :) OK

**Comment by frigierim** [comment]
Fatto! XD

**Comment by CristiJ92** [comment]
ottimo, ma resetta la partita! XD

> altre feature:
> 
> * X, Y e rotazione attuale stampate su schermo OK

sarebbe utile anche la rotazione attuale

**Comment by CristiJ92** [comment]
> Sarebbe utile avere qualche cheat ai fini di debug/testing...
> 
> al momento mi viene da proporre:
> -solo jhon OK
> -solo kenny OK
> -speed OK

il valore speed a cosa corrisponde? ha qualche relazione con le misure km/h, m/s o cosa?

**Comment by CristiJ92** [comment]
richiesta features:
- vai a main menu 
- riavvia game OK

**Comment by frigierim** [comment]
Purtroppo la visualizzazione delle maschere di collisione funziona solo dopo che una scena viene ricaricata, quindi ho fatto in modo che lo rifaccia in automatico - ma questo resetta la partita. Aggiungerò la rotazione, anche se quella dovrebbe essere abbastanza evidente anche dal punto di vista visivo. Speed è il valore che viene moltiplicato per il tempo per calcolare la distanza percorsa dal personaggio, ed approssimativamente è in pixels/secondo. Riavvia game lo metto immediatamente, tanto è veloce; vai a main menu secondo me avrebbe più senso come parte del gioco, non del menù di debug, ma dimmi tu come la vedi.

**Comment by CristiJ92** [comment]
> Purtroppo la visualizzazione delle maschere di collisione funziona solo dopo che una scena viene ricaricata, quindi ho fatto in modo che lo rifaccia in automatico - ma questo resetta la partita. 

nessun escamotage?? :(

>Aggiungerò la rotazione, anche se quella dovrebbe essere abbastanza evidente anche dal punto di vista visivo. 

il problema è che può non essere chiaro in quanto la schermata nasconde il personaggio e se devo indicare una direzione viene complicato

>Speed è il valore che viene moltiplicato per il tempo per calcolare la distanza percorsa dal personaggio, ed approssimativamente è in pixels/secondo.

considerando che **attualmente** 1Tile=1m^2 puoi fare una funzione per dare in pasto al gioco una velocità più umana? XD 
mi sarebbe utile una velocità standard ai fini di bilanciamento 

>Riavvia game lo metto immediatamente, tanto è veloce; 

:)

>vai a main menu secondo me avrebbe più senso come parte del gioco, non del menù di debug, ma dimmi tu come la vedi.

la penso come te ma al momento non c'è una schermata di pausa e al momento non è una priorità... vedi te cosa vuoi fare

**Comment by CristiJ92** [comment]
richiesta features:
- "observable game world " (FOV?)

a proposito di questo: al momento (V.0.0.8) varia in base alla dimensione della finestra... puoi fixare la visuale e farmi avere i valori corrispondenti per le visuali da finestra a full scheen del 1080p precedente all'update?

**Comment by CristiJ92** [comment]
> ottimo, ma resetta la partita! XD
> 
> > altre feature:
> > 
> > * X, Y e rotazione attuale stampate su schermo OK
> 
> sarebbe utile anche la rotazione attuale

da fermo mostra "idle" e non la direzione attuale, se vuoi metti pure lo stato attuale del personaggio ma mi serve l'ultima direzione presa se no mi devo per forza muovere e viene complicato fare screen

**Comment by CristiJ92** [comment]
@frigierim  ho editato i miei post per semplificarti la vita... o almeno spero XD

ad ogni feature aggiunta al gioco ho messo un "OK", a quella da perfezionare "WIP" e quelle ancora non aggiunte le ho lasciate vuote

userò questa convenzione da ora in poi

**Comment by CristiJ92** [comment]
richiesta feature:
- scelta livello tra tutti quelli a disposizione nella cartella "Levels" (menu tendina?) OK

**Comment by CristiJ92** [comment]
> richiesta feature:
> 
> * scelta livello tra tutti quelli a disposizione nella cartella "Levels" (menu tendina?) OK

non vedo il nuovo livello che avevo creato, il menu è dinamico o preimpostato da te?

**Comment by frigierim** [comment]
Purtroppo non basta mettere un nuovo livello Tiled nella cartella assets/Levels, bisogna anche creare il corrispondente livello di gioco in Godot nella cartella scenes/floors. Fortunatamente non è molto complicato da fare, basta copiare uno di quelli esistenti e sostituire la mappa con una nuova dalla cartella Levels. Fatemi sapere se vi serve una mano per farlo, ma dovrebbe essere semplice da fare anche senza competenze di programmazione. Una volta che il nuovo livello di Godot è creato, dopo posso fare in modo che la lista nella schermata di debug si aggiorni automaticamente.

**Comment by CristiJ92** [comment]
ok, facendo così puoi fare un menu dinamico di scenes/floors?

**Comment by frigierim** [comment]
Yes, appena creata la nightly per supportarlo. Per vedere nuovi livelli:

- creare un nuovo layout in Tiled, e metterlo in una cartella dedicata in Assets/Levels
- creare un nuovo livello Godot (copiandone uno esistente) in una cartella dedicata in scenes/floors; il nome di questa cartella comparirà nel menu a tendina, e deve essere lo stesso del file .tscn di Godot
- aggiungere una riga in scenes\level\level.gd dentro all'array levels:
```
var levels = [  preload("res://scenes/floors/giardino/giardino.tscn").instance(),
		      preload("res://scenes/floors/ground/ground.tscn").instance(),
                       preload("res://scenes/floors/newlevel/newlevel.tscn").instance() 
]
```
A breve proverò a semplificare il processo in modo da non dover nemmeno modificare quest'ultimo array.

**Comment by frigierim** [comment]
Dalla versione 0.0.12 non è più necessario modificare l'array di cui parlavo al post precedente, per aggiungere un nuovo livello. Basta mettere la mappa Tiled e le sue risorse in una cartella dedicata in assets\levels, e in scenes\floors creare una scena Godot un una cartella dedicata (la scena deve avere lo stesso nome della cartella in cui risiede). In questo modo dovrebbe comparire automaticamente nel menu a tendina di debug.

**Comment by frigierim** [comment]
Ho aggiunto un menu durante il gioco per poter uscire dalla partita corrente, si attiva usando ESC. Questo però ha innescato un conflitto con il menu di debug esistente, quindi ho cambiato la modalità di attivazione della finestra dei cheat che ora richiede la combinazione di tasti Shift+F10. Ditemi se va bene o se preferite fare diversamente. Inoltre, non so quale pulsante del joypad associare per attivare il menu in-game.

**Comment by CristiJ92** [comment]
v.0.0.14:
selezione livello non worka
![image](https://user-images.githubusercontent.com/45758943/54994152-d60e7700-4fc3-11e9-8c7d-4054c3ede6c5.png)

**Comment by CristiJ92** [comment]
> Ho aggiunto un menu durante il gioco per poter uscire dalla partita corrente, si attiva usando ESC. Questo però ha innescato un conflitto con il menu di debug esistente, quindi ho cambiato la modalità di attivazione della finestra dei cheat che ora richiede la combinazione di tasti Shift+F10. Ditemi se va bene o se preferite fare diversamente. Inoltre, non so quale pulsante del joypad associare per attivare il menu in-game.

aggiornato il GDD con i comandi

**Comment by frigierim** [comment]
Per favore, verifichiamo cosa manca ma chiudiamo questo mostro di issue. I punti che rimangono aperti daranno origine a nuovi issue individuali, altrimenti non capisco mai cosa rimane fuori e cosa è sistemato senza rileggermi tutto il thread (nonostante i WIP).

**Comment by CristiJ92** [comment]
Sono d'accordo sul fatto che c'è un po di confusione ma credo che questo issue dovrebbe rimanere sempre aperto perchè potremmo avere bisogno in futuro di ulteriori cheat ecc...
Se vuoi cambiamo convenzione, ogni volta che verifico riassumo le features richieste e cambio la Milestone di questo issue in "Release".
Mantengo l'eventuale tag "WIP" se c'è da modificare la feature richiesta


V.0.0.16
features richieste:
- valore speed in misura standard
- "observable game world" (FOV? Zoom?)

**Comment by frigierim** [comment]
Tutte le richieste dovrebbero essere a posto ora. Ma se invece creassimo un issue per ciascuna feature richiesta e usassimo la label Debug per tutte quelle che fanno parte di questa categoria, non cambierebbe molto (se non che riusciremmo a tracciarle individualmente, senza dover rileggere il muro di post). Comunque, per me vanno bene entrambe le maniere.

**Comment by CristiJ92** [comment]
v.0.0.17

ok facciamo come dici tu, sistemate le ultime cose chiudiamo

- cappare lo zoom max in base alla grandezza della mappa, permettere di sbloccare questo limite con un check :)

altre richieste in nuovi issue.

**Comment by frigierim** [comment]
Aggiunto il cap.
