### ISSUE TITLE
indagare sulle collisioni (o non) anomale con alcuni oggetti nella scena

### ISSUE THREAD

**Issue by CristiJ92** [frigierim/ggj-tracking#26]
V.0.0.7
ci sono diverse anomalie sulle collisioni, bisogna capire il problema, non è necessario fixare per forza su questo livello in quanto verrà cambiato.

![image](https://user-images.githubusercontent.com/45758943/54601624-c630e900-4a3f-11e9-9e4c-fe6c395af357.png)

![image](https://user-images.githubusercontent.com/45758943/54601774-363f6f00-4a40-11e9-9fe8-c1c6a523b441.png)

![image](https://user-images.githubusercontent.com/45758943/54601807-4b1c0280-4a40-11e9-9c0f-c782b58e5d63.png)

![image](https://user-images.githubusercontent.com/45758943/54601900-7b63a100-4a40-11e9-8f90-127c7e36996c.png)
![image](https://user-images.githubusercontent.com/45758943/54601929-8e767100-4a40-11e9-9d33-dfb2b0c1f216.png)

![image](https://user-images.githubusercontent.com/45758943/54601980-b4037a80-4a40-11e9-9e27-39adde2c5ab3.png)

![image](https://user-images.githubusercontent.com/45758943/54602003-bfef3c80-4a40-11e9-8094-dddfd0ab0fbe.png)
![image](https://user-images.githubusercontent.com/45758943/54602014-c8e00e00-4a40-11e9-8d52-fe9e38760d2a.png)

![image](https://user-images.githubusercontent.com/45758943/54602077-e9a86380-4a40-11e9-8e90-2ddba3750b16.png)

![image](https://user-images.githubusercontent.com/45758943/54602131-19576b80-4a41-11e9-94e1-aebb577de655.png)

![image](https://user-images.githubusercontent.com/45758943/54602151-24aa9700-4a41-11e9-895d-1723d6936bab.png) e su tutto il tavolo/sedie

![image](https://user-images.githubusercontent.com/45758943/54602193-4dcb2780-4a41-11e9-8fee-e813509606b4.png) stessa cosa

**Comment by frigierim** [comment]
Siccome la Nightly viene rilasciata con una build di debug, è possibile usare questo comando:
Nightly.exe --debug-collisions
per mostrare a video un overlay con le maschere di collisione che ho usato. Dovrebbe essere abbastanza semplice individuare i problemi reali, così. Ovviamente, ha senso farlo quando la mappa è quella definitiva.

**Comment by CristiJ92** [comment]
lol si può avere nei cheat? XD (aggiungo al relativo post)

btw il problema rimane, le collisioni non corrispondono all'overlay

**Comment by CristiJ92** [comment]
V.0.0.9:
@frigierim ti ho riassegnato perchè il problema non è grafico, ci sono delle collisioni che spuntano dal nulla nelle coordinate che ti ho segnalato

vedi esempio: 

![image](https://user-images.githubusercontent.com/45758943/54770188-09878500-4c03-11e9-8b12-4b88cd3f4557.png)


![image](https://user-images.githubusercontent.com/45758943/54769993-a990de80-4c02-11e9-9b54-d5aac58cc769.png)

**Comment by CristiJ92** [comment]
V.0.0.26

@frigierim  hai trovato il problema?

**Comment by CristiJ92** [comment]
V.0.1.1
sembra risolto, chiudo... cos'era sto fantasma?
