### ISSUE TITLE
Moonwalker

### ISSUE THREAD

**Issue by CristiJ92** [frigierim/ggj-tracking#28]
v0.0.15:

bhe... si può fare il moonwalk con la tastiera...

https://youtu.be/b6pomaq30Gg?t=95

step:
1)avvia gioco
2)play
3)usare cheat solo X per semplificare la vita
4)andare in una direzione e successivamente premere ANCHE il tasto per la direzione opposta

fa anche in diagonale :)

**Comment by frigierim** [comment]
A parte che il moonwalk è sempre molto scenografico... come ha senso comportarsi in caso di input contrastanti? Tengo buono l'ultimo?

**Comment by CristiJ92** [comment]
direi idle rivolto verso l'ultima direzione prima dell'arresto... 

reminder: aggiornare GDD
