### ISSUE TITLE
Jhonny è diventato "negro"? XD

### ISSUE THREAD

**Issue by CristiJ92** [frigierim/ggj-tracking#30]
lo sprite di jhonny si è scurito, che è successo?

![image](https://user-images.githubusercontent.com/45758943/54994249-1a017c00-4fc4-11e9-8b2e-af82cf5bed80.png)

![image](https://user-images.githubusercontent.com/45758943/54994308-3d2c2b80-4fc4-11e9-885c-528699d0d3b5.png)

**Comment by frigierim** [comment]
Eh, ho visto anch'io... verifico quando è successo. Male che vada, gli facciamo ottenere la cittadinanza italiana.
