### ISSUE TITLE
GUI sballata se finestra non ha la dimensione prefissata

### ISSUE THREAD

**Issue by CristiJ92** [frigierim/ggj-tracking#33]
![image](https://user-images.githubusercontent.com/45758943/54687988-1a5dcb00-4b1d-11e9-9025-99d850c17c5e.png)

![image](https://user-images.githubusercontent.com/45758943/54688140-5db83980-4b1d-11e9-9dbe-42e571895b1b.png)

![image](https://user-images.githubusercontent.com/45758943/54688872-c7851300-4b1e-11e9-8200-a3529037b7d8.png)

**Comment by CristiJ92** [comment]
quì c'è da capire cosa bisogna fare e quali scelte di design fare...

al momento direi semplicemente di fixare la dimensione e la posizione degli oggetti (text video buttons).

per conoscenza: a tempo debito aprirò issues per bloccare la finestra a quella dimensione e una richiesta all'issue #8 per poter sboccare questo limite

**Comment by frigierim** [comment]
Ho cambiato i parametri dell'app in modo che venga scalato tutto quanto insieme; non è che sia una soluzione, ma intanto potete vedere come funziona.

**Comment by CristiJ92** [comment]
va bene era proprio quello che intendevo

in issue #8 chiedevo:
> richiesta features:
> 
> * "observable game world " (FOV?)
> 
> a proposito di questo: al momento (V.0.0.8) varia in base alla dimensione della finestra... puoi fixare la visuale e farmi avere i valori corrispondenti per le visuali da finestra a full scheen del 1080p precedente all'update?

riesci a ricavare i 2 valori adesso?

**Comment by frigierim** [comment]
Se parli della versione che avevamo fatto alla GGJ, prima di dimezzare le dimensioni di tutti gli assets, erano 1920x1080.

**Comment by CristiJ92** [comment]
parlo della v.0.0.8, ingrandendo la finestra a schermo intero si ha una visuale più estesa il che mi interessa, per questo ti ho chiesto questa feature in #8 , inoltre i valori che ti chiedo sono quelli della visuale corrente fixata e quella della visuale fullscreen 1080p che avevamo in v.0.0.8 (se riesci a ricavarlo).

se vuoi approfondire la richiesta ne parliamo nell'issue #8 

chiudo visto che il task è completato

**Comment by CristiJ92** [comment]
@frigierim sai dirmi quali sono le dimensioni della finestra quando viene avviato il gioco?

**Comment by frigierim** [comment]
Dovrebbero essere 1920x1080

**Comment by CristiJ92** [comment]
v.0.1.2
nope, è una finestra 16:9 ma non 1920x1080. La dimensione è ok ma mi serve scriverlo in GDD quanto è

**Comment by frigierim** [comment]
Hai ragione, non so quando ho cambiato ma ora le dimensioni dovrebbero essere 1024x640.
