### ISSUE TITLE
Video Main Menu mancante

### ISSUE THREAD

**Issue by CristiJ92** [frigierim/ggj-tracking#35]
Audio mancante nel video del Main Menu

step:
1)Avviare gioco
2)Stare nel Main Menu

**Comment by frigierim** [comment]
In realtà nemmeno nell'originale c'era l'audio nel menú principale, solo il sibilo fastidioso quando iniziava il gioco che poi non smetteva più di suonare (e quindi ce lo ritrovavamo anche nel menú, quando qualcuno vinceva il gioco e ci si ritornava). Come vogliamo gestirlo?

**Comment by CristiJ92** [comment]
Resettiamo l'issue e vediamo come va...

V. 0.0.4:
Video Mancante nel main menu, rinomino issue.
