### ISSUE TITLE
Impossibile iniziare il gameplay

### ISSUE THREAD

**Issue by CristiJ92** [frigierim/ggj-tracking#36]
V. 0.0.6:
non è possibile cliccare sul bottone "Play" e iniziare a giocare.
inoltre bisognerebbe aggiungere un pulsante di conferma per il gamepad (XBox360 "A") per il main menu.
Credo che il bug sia stato introdotto per via della schermata dei cheat

Step:
1)avvia gioco
2)tentare di cliccare il bottone "Play"

**Comment by frigierim** [comment]
Non ho testato con il controller, ma la tastiera dovrebbe funzionare... I tasti di selezione sono gli stessi di conferma durante il gioco, quindi INVIO e SPAZIO. Vanno bene o devo cambiarli?

**Comment by CristiJ92** [comment]
ok hai ragione, non funziona più il mouse allora e bisogna aggiungere il tasto di conferma al controller nel main menu.

**Comment by frigierim** [comment]
Sistemato in versione 0.0.7
