### ISSUE TITLE
Comandi Jhon e Kenny scambiati

### ISSUE THREAD

**Issue by CristiJ92** [frigierim/ggj-tracking#37]
Jhon (biondo) comandato col lato dx del pad e tastiera
Kenny (rosso) comandato col lato sx del pad e tastiera

in realtà da design è il contrario: 
biondo SINISTRA 1st player
rosso DESTRA 2nd player

step:
1)Avvia gioco
2)Play
3)Bug presente durante il gameplay

**Comment by frigierim** [comment]
Sistemato in https://github.com/frigierim/ggj-ng/commit/8ac95021d13a692972f4d0a7e58579d23f95599a

**Comment by CristiJ92** [comment]
V. 0.0.4:

i tasti "conferma" possono essere usati indifferentemente sia da jhonny che da kenny a prescindere se è il loro turno o no

step:
1)avvia il gioco
2)Play
3)raccogliere un foglio con jhonny e usare il bottone "conferma" di kenny o viceversa
