### ISSUE TITLE
Problema nella visualizzazione delle Tiles

### ISSUE THREAD

**Issue by CristiJ92** [frigierim/ggj-tracking#42]
Le Tiles Presentano diversi problemi di visualizzazione, si notano contorni e/o non scorrono in modo fluido

step:
1)Avvia Gioco
2)Play
3)fare gameplay per visualizzare bug

**Comment by frigierim** [comment]
Il problema è dovuto all'importazione di Godot. Per risolverlo è sufficiente andare nella cartella assets/Levels, selezionare ciascuna immagine PNG, disabilitare il checkbox Filter nell'inspector, e premere il pulsante "Reimport" sempre nell'inspector.

**Comment by CristiJ92** [comment]
Non riesco a seguirti: "disabilitare il checkbox Filter nell'inspector, e premere il pulsante "Reimport" sempre nell'inspector."

In ogni caso, quando fai commit puoi fare anche la relativa build? così testo direttamente l'eseguibile e non dovrebbero esserci problemi in futuro (forse). Magari cominciamo anche a numerare la versione corrente e stamparla sulla UI da qualche parte...

**Comment by frigierim** [comment]
Intendo così:

![immagine](https://user-images.githubusercontent.com/8074805/54285393-29370180-45a2-11e9-9f89-3b57efeef936.png)

![immagine](https://user-images.githubusercontent.com/8074805/54285450-466bd000-45a2-11e9-8d17-e2b099dcc107.png)

Posso anche creare l'eseguibile, ma ho paura che il repository esploda, visto che GitHub poi si tiene tutte le versioni dello storico in pancia e quando scarichi per la prima volta ci vogliono dei mesi. Guardo se c'è modo di fargli fare dei nightly build da tenere fuori dal repository...

**Comment by frigierim** [comment]
Ora che ho fatto le nightly build, dovresti poter verificare che la versione compilata non abbia i problemi di visualizzazione. Dovresti poterla scaricare dalla schermata "Releases"...
